
services:

  flask-app:

    build: .
    container_name: my_app
    depends_on: 
      - mongodb
    restart: "on-failure"
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017  
      - MONGO_USER=mongo-user
      - MONGO_PASS=mongo-password

    ports: 
      - "5000:5000"

    

  mongodb:

    image: mongo:5.0
    container_name: mongodb 
    restart : "on-failure"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    

volumes:
  mongo-data:
    driver: local