apiVersion: v1
kind: ReplicationController
metadata:
  name: todo-rc
  labels:
    app: todo-app-rc
    tier: frontend-rc
spec:
  replicas: 2
  selector:
    app: todo-app-rc
    tier: frontend-rc
  template:
    metadata:
      labels:
        app: todo-app-rc
        tier: frontend-rc
    spec:
      containers:
      - name: flask-todo-rc
        image: arr8154/todo-flask-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_HOST
          value: mongodb
        - name: MONGO_PORT
          value: "27017"
        - name: FLASK_ENV
          value: production
